[package]
name = "redmine-api"
description = "API for the Redmine issue tracker"
readme = "README.md"
license = "MIT/Apache-2.0"
version = "0.1.1"
authors = ["Matthias Hörmann <mhoermann@gmail.com>"]
repository = "https://github.com/taladar/redmine-api"
keywords = [ "redmine", "api" ]
categories = [ "api-bindings" ]
edition = "2021"
exclude = [ ".env", "tarpaulin-report.html", "tarpaulin-report.json" ]

[profile.release]
# do not strip debug info from release builds, useful for debugging those, cargo-flamegraph profiling or similar use cases
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.thiserror]
version = "~1.0"

[dependencies.futures]
version = "~0.3"

[dependencies.tracing]
version = "~0.1"
features = [ "log" ]

[dependencies.reqwest]
version = "~0.11"
features = [ "blocking", "json" ]

[dependencies.time]
version = "~0.3"
features = [ "serde", "serde-human-readable" ]

[dependencies.url]
version = "~2"

[dependencies.serde]
version = "~1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "~1.0"

[dependencies.serde_with]
version = "~1.11"

[dependencies.envy]
version = "~0.4"

[dependencies.http]
version = "~0.2"

[dependencies.derive_builder]
version = "~0.10"

[dependencies.derivative]
version = "~2.2"

[dependencies.bytes]
version = "~1.1"

[dev-dependencies.pretty_assertions]
version = "~1.0"

[dev-dependencies.dotenv]
version = "~0.15"

[dev-dependencies.tracing-test]
version = "~0.2"

[dev-dependencies.function_name]
version = "~0.2"

[dev-dependencies.finally-block]
version = "~0.2"

[dev-dependencies.parking_lot]
version = "~0.11"
