[package]
name = "redmine-api"
description = "API for the Redmine issue tracker"
readme = "README.md"
license = "MIT/Apache-2.0"
version = "0.1.5"
authors = ["Matthias Hörmann <mhoermann@gmail.com>"]
repository = "https://github.com/taladar/redmine-api"
keywords = [ "redmine", "api" ]
categories = [ "api-bindings" ]
edition = "2021"
exclude = [ ".env", "tarpaulin-report.html", "tarpaulin-report.json" ]

[profile.release]
# do not strip debug info from release builds, useful for debugging those, cargo-flamegraph profiling or similar use cases
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror= "1.0.31"
futures= "0.3.21"
url= "2.2.2"
serde_json= "1.0.81"
serde_with= "1.13.0"
envy= "0.4.2"
http= "0.2.7"
derive_builder= "0.11.2"
derivative= "2.2.0"
bytes= "1.1.0"

[dependencies.tracing]
version = "0.1.34"
features = [ "log" ]

[dependencies.reqwest]
version = "0.11.10"
features = [ "blocking", "json" ]

[dependencies.time]
version = "0.3.9"
features = [ "serde", "serde-human-readable" ]

[dependencies.serde]
version = "1.0.137"
features = [ "derive" ]

[dev-dependencies]
pretty_assertions= "1.2.1"
dotenv= "0.15.0"
tracing-test= "0.2.1"
function_name= "0.2.1"
finally-block= "0.2.0"
parking_lot= "0.12.0"
